#!/bin/bash
#######################################################
# HocVPS Script Installer v1.1
# To install HocVPS Script type: 
# curl -sO https://hocvps.com/install && bash install
#######################################################

if [ $(id -u) != "0" ]; then
    printf "You need to be root to perform this command. Run \"sudo su\" to become root!\n"
    exit
fi

if [ -f /etc/hocvps/scripts.conf ]; then
	echo "========================================================================="
	echo "Server/VPS cua ban da cai san HocVPS Script"
	echo "Hay su dung lenh hocvps de truy cap menu quan ly"
	echo "Chao tam biet !"
	echo "========================================================================="
exit
fi

rm -f install*

cd /root/

rm -f install*

if [ "$1" = "wordpress" ]; then
	curl -sO https://hocvps.com/scripts/$(cat /etc/redhat-release | grep -o '[0-9]\.[0-9]')/install && bash install wordpress
else
	curl -sO https://hocvps.com/scripts/$(cat /etc/redhat-release | grep -o '[0-9]\.[0-9]')/install && bash install
fi